### ISSUE TITLE
Contextual Consent Contao Integration

### ISSUE THREAD

**Issue by simonla82** [pdir/klaro-consent-manager#1]
**What do I want to do?**

I want to use the `contextualConsentOnly` option for a service and mark content elements as related to that service (e.g., a YouTube video embedding should only load after the user clicked "agree").

**What is the problem?**

The problem is split in two parts:

1. The visibility depending on consent option only shows on content elements of type `text`.
2. Linking a content element (of type `text`) to a Klaro service does not correctly set the required `data-name` attribute.

**What is the desired behaviour?**

1. All contents element should support being linked to a Klaro service.
2. Linking to a Klaro service should cause the `data-name` attribute to be set to that service name, and - if required - set the `data-src` attribute as necessary.

**Additional Information:**

What I want to have on all content elements:
![grafik](https://user-images.githubusercontent.com/73082071/216189403-4b9e12f8-13ca-4672-9ec8-9e48eb2e9a5a.png)

The corresponding section on the `YouTube` content element:
![grafik](https://user-images.githubusercontent.com/73082071/216189692-e2fdd47f-6aa0-449e-93b9-831983f38a87.png)

The output when linking a text element to a Klaro service:
```html
<div class="column content-text">
<h2>...</h2>
<p>some text</p>
</div>
```

The desired output:
```html
<div class="column content-text" data-name="youtube">
<h2>...</h2>
<p>some text</p>
</div>
```

**Setup:**

- Contao 5.0.3
- PHP 8.1
- NATURE Theme 2.4.2
- Klaro Consent Manager 1.0.3

I appreciate any support and I am open for questions!

**Comment by cmette** [comment]
Hi - the feature is in the works right now. But it concerns not exactly documented and partly experimental code in klaro and needs some time for implementation. We are working on it.

**Comment by MDevster** [comment]
Fixed in version 1.1.2

**Comment by simonla82** [comment]
Thank you for your effort! For me, unfortunately, it does not work completely yet:

The first part of the issue seems to be resolved: The "visibility depending on consent"-option now shows for all elements. However, the element shows independent of the option I select there:

Setting the following option

![grafik](https://user-images.githubusercontent.com/73082071/226560422-75e5dc4e-8762-43f4-86bd-c1181b6f441d.png)

and having disabled the youtube service

![grafik](https://user-images.githubusercontent.com/73082071/226560671-57cacd47-9d55-4bfa-a390-533d109c9049.png)

causes the youtube video to show on the website nonetheless. I think this is caused by the fact that neither the `data-name` nor the  `data-src` attribute is set in the resulting HTML code, as shown below:

```html
<iframe src="https://www.youtube.com/embed/dQw4w9WgXcQ" allowfullscreen="" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" width="" height=""></iframe>
```

Did I miss something?

**Comment by cmette** [comment]
Hello and thank you for your feedback. I will have another look at this soon. Please be patient.
