### ISSUE TITLE
Version 1.1 breaks with Contao 5.0

### ISSUE THREAD

**Issue by simonla82** [pdir/klaro-consent-manager#2]
## Bug description

Installing klaro-consent-manager v 1.1 with Contao 5.0 not possible

## Steps to reproduce

Install Contao 5.0 and try to install klaro-consent-manager v1.1

## Expected behavior

Should be installable

## Screenshots

Executing 

```
composer update pdir/klaro-consent-manager contao/conflicts --no-install --dry-run
```
yields

```
> Resolving dependencies using Composer Cloud v3.5.1
[6.8MiB/0.19s] Loading composer repositories with package information
[59.7MiB/6.55s] Updating dependencies
[78.1MiB/6.77s] Your requirements could not be resolved to an installable set of packages.
[78.1MiB/6.77s] 
  Problem 1
    - menatwork/contao-multicolumnwizard-bundle[3.5.7, ..., 3.5.9] require contao/core-bundle ^4.9 -> found contao/core-bundle[4.9.0, ..., 4.13.16] but these were not loaded, likely because it conflicts with another require.
    - pdir/klaro-consent-manager[1.1.0, ..., 1.1.1] require menatwork/contao-multicolumnwizard-bundle ^3.5.7 -> satisfiable by menatwork/contao-multicolumnwizard-bundle[3.5.7, 3.5.8, 3.5.9].
    - Root composer.json requires pdir/klaro-consent-manager ^1.1 -> satisfiable by pdir/klaro-consent-manager[1.1.0, 1.1.1].
[78.1MiB/6.77s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[34.8MiB/6.80s] Memory usage: 34.77MB (peak: 167.14MB), time: 6.81s.
[34.8MiB/6.80s] Finished Composer Cloud resolving.
```

## Environment

- Contao 5.0.3
- PHP 8.1.12
- Contao Manager 1.6.3

**Comment by cmette** [comment]
Hello - of course - this is a known bug and will be fixed soon.

**Comment by MDevster** [comment]
We are waiting for the release of this branch https://github.com/menatwork/contao-multicolumnwizard-bundle/tree/feature/contao-5-support.
As a temporary solution the following can be used in composer.json:

`"menatwork/contao-multicolumnwizard-bundle": "dev-feature/contao-5-support as 3.5.7"`

We and [zonky2](https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/13) have tested it and everything works as desired.

**Comment by MDevster** [comment]
The customization is now no longer necessary, a new version of the contao-multicolumnwizard-bundle has been released
https://github.com/menatwork/contao-multicolumnwizard-bundle/releases/tag/3.6.0
